apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: halo-backend
  namespace: halo-backend
  annotations:
    kubernetes.iop/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  rules:
  - host: api.millennium.sh
    http:
      paths:
      - path: /halo
        pathType: Prefix
        backend:
          service:
            name: halo-backend
            port:
              number: 80
  tls:
    - hosts:
        - api.millennium.sh
---
apiVersion: v1
kind: Service
metadata:
  name: halo-backend
  namespace: halo-backend
spec:
  selector:
    app:  halo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halo-backend-deployment
  namespace: halo-backend
spec:
  selector:
    matchLabels:
      app: halo-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: halo-backend
    spec:
      containers:
      - name: halo-backend
        image: gusbell/halo:1.0.0
        ports:
        - containerPort: 4000
