name: Deploy
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
    - uses: deploys-app/deploys-action@v1
      with:
        project: ${{ secrets.PROJECT_ID }}
        location: ${{ secrets.LOCATION }}
        name: ${{ secrets.DEPLOYMENT_NAME }}
        image: ghcr.io/${{ github.repository }}@${{ steps.docker_build.outputs.digest }}
      env:
        DEPLOYS_AUTH_USER: ${{ secrets.DEPLOYS_AUTH_USER }}
        DEPLOYS_AUTH_PASS: ${{ secrets.DEPLOYS_AUTH_PASS }}
